### ISSUE TITLE
Security issue with evaluating code

### ISSUE THREAD

**Issue by kav2k** [Shifterovich/Firemark#2]
You let the user evaluate arbitrary code using `input()`. This is _quite bad_.

A user can input any code and it will be executed.

Not to mention it makes zero sense for the user to have to type the whole `pixelMap` to enter 1 bit worth of data.

You should always use safe input methods, treat everything as a string and convert it explicitly.

**Comment by kav2k** [comment]
Oh, yes, and it's Python 3 incompatible, since they got rid of the silly `input()` function that now works as `raw_input()`

**Comment by Shifterovich** [comment]
I could make a Python 3 version.
But it would require more than just editing inputs.
`python3 firemark.py 
Traceback (most recent call last):
  File "firemark.py", line 1, in <module>
    import Image
ImportError: No module named 'Image'`

**Comment by kav2k** [comment]
True, TIL is not ported to Python 3.

The issue with arbitrary code evaluation still stands - use `input_raw` then.
